project:
  type: website
  output-dir: docs

website:
  title: "HenokDawite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu: 
          - href: Valentines Day Gifts.qmd
            text: Gift Giving
          - href: Meteorite falls.qmd
            text: Meteorite Falls
          - href: Project 2.qmd
            text: Netflix Movies/TV
          - href: Project 3.qmd
            text: Free Throw Rate & Tourney Odds
          - href: Project4.qmd
            text: Havasupai Tribe v. Arizona Board of Regents
          - href: Project5.qmd
            text: Exploring U.S. Policing Trends Through Data

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
