project:
  type: website
  output-dir: docs

website:
  title: "HenokDawite"
  navbar:
    background: "#1b2a49"
    left:
      - href: index.qmd
        text: Home
      - href: Resume.qmd
        text: Resume
      - text: Projects
        menu: 
          - href: Valentines Day Gifts.qmd
            text: Gift Giving
          - href: Meteorite falls.qmd
            text: Meteorite Falls
          - href: Project 2.qmd
            text: Netflix Movies/TV
          - href: Project 3.qmd
            text: Free Throw Rate & Tourney Odds
          - href: Project4.qmd
            text: Havasupai Tribe v. Arizona Board of Regents
          - href: Project5.qmd
            text: Exploring U.S. Policing Trends Through Data
          - href: DS02Prezi.qmd
            text: DS Presentation

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true

editor: visual
