project:
  type: website
  output-dir: docs

website:
  title: "HenokDawite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - menu: 
        - href: Valentines Day Gifts.qmd
          text: Gift Giving
        - href: Meteorite falls.qmd
          text: Meteorite Falls
        - href: Project 2.qmd
          text: Netflix Movies/TV

format:
  html:
    theme: cosmo
    toc: true

editor: visual

